### ISSUE TITLE
JetBrains plugins note...

### ISSUE THREAD

**Issue by bhutten** [edcs/edcs.github.io#2]
Hi - I used your https://edcs.me/blog/setting-up-xdebug-with-phpstorm-and-laravel-homestead/ tutorial with IntelliJ and needed to install the "PHP Remote Interpreter" and "Vagrant" plugins in order to get the UI/functionality described in your tutorial.

Once I did that the tutorial worked perfectly - thanks!

**Comment by edcs** [comment]
Thanks for the tip 🎉 - I'll update the article when I have a chance!
